# Generated by Django 5.0 on 2023-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.TextField(default='Mostafa Ali'),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.TextField(default='Monowara Begum'),
        ),
    ]
