# Generated by Django 5.0 on 2023-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_student_fathers_name_student_mothers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelTeacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
