# Generated by Django 5.0 on 2024-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50, verbose_name='Task Title')),
                ('taskDescription', models.TextField(verbose_name='Task Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('TaskAssignDate', models.DateField(verbose_name='Task Assign Date')),
                ('category', models.ManyToManyField(related_name='tasks', to='category.taskcategory')),
            ],
        ),
    ]
